version: '3'

volumes:
  dbdata:
    driver: local

networks:
  backend:
    driver: bridge

services:
  app:
    build:
      context: .
    container_name: kanban_backend
    restart: unless-stopped
    working_dir: /app
    environment:
      PORT: 3000
    volumes:
      - ./:/app
    ports:
      - "9090:3000"
    networks:
      - backend
    depends_on:
      - db 

  db:
    image: mongo:6.0.3
    restart: unless-stopped
    container_name: kanban_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME:-user}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD:-password}"
    ports:
      - "${DB_PORT:-27017}:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - backend
